server:
  port: 7201
spring:
  application:
    name: Gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  redis:
    port: 6379
    host: 127.0.0.1
    database: 1
    timeout: 10s
    lettuce:
      pool:
        max-active: 200
        min-idle: 0
logging:
  level:
    org.springframework.cloud.gateway: debug
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.netty: debug
# actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  instance:
    instance-id: Gateway
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 3
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8001/eureka