server:
  port: 7202
eureka:
  instance:
    instance-id: consumer
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 3
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8001/eureka
spring:
  application:
    name: consumer